// Mocks generated by Mockito 5.4.6 from annotations
// in book_finder/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:book_finder/data/datasource/app_offline_datasource.dart' as _i4;
import 'package:book_finder/data/datasource/app_remote_datasource.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRemoteDataSource extends _i1.Mock
    implements _i2.AppRemoteDataSource {
  MockAppRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getSearchedBooks(
    String? title,
    int? offset,
    int? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchedBooks, [title, offset, page]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [AppOfflineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppOfflineDataSource extends _i1.Mock
    implements _i4.AppOfflineDataSource {
  MockAppOfflineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> addBook(Map<String, dynamic>? book) =>
      (super.noSuchMethod(
            Invocation.method(#addBook, [book]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<String, dynamic>?> getBookById(int? bookCoverId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookById, [bookCoverId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}
